

interface Joystick {
	[Static] int count();
	[Static] Joystick open(int idx );

	void close(  );
	int getAxis(  int axisId ) ;
	int getHat(  int hatId );
	bool getButton(  int btnId );
	int getId(  );
	String getName(  );
};
